module.exports = {
    theme: ["ThemeProvider"],
    foundations: ["GridContainer", "GridItem", "Icon", "LazyImage", "Page", "Typography"],
    components: [
        "Accordion",
        "AccordionSection",
        "Breadcrumbs",
        "Button",
        "Checkbox",
        "CheckboxGroup",
        "DataTable",
        "DatePicker",
        "Drawer",
        "DynamicDropdown",
        "FileUpload",
        "LayoutCell",
        "LayoutGroup",
        "LayoutTable",
        "Link",
        "LoadingOverlay",
        "LoadingSpinner",
        "Menu",
        "Modal",
        "OverflowMenu",
        "Pagination",
        "PanelMenu",
        "Radio",
        "RadioGroup",
        "Select",
        "TabGroup",
        "Tab",
        "Tag",
        "TextField",
        "TextArea",
        "Toast",
        "TokenExFrame",
        "Tooltip",
    ],
    utilities: ["Clickable", "Hidden", "VisuallyHidden"],
};
