import AccountSettingsState from "@insite/client-framework/Store/Pages/AccountSettings/AccountSettingsState";
import AddressesState from "@insite/client-framework/Store/Pages/Addresses/AddressesState";
import BrandsState from "@insite/client-framework/Store/Pages/Brands/BrandsState";
import BudgetManagementState from "@insite/client-framework/Store/Pages/BudgetManagement/BudgetManagementState";
import CartState from "@insite/client-framework/Store/Pages/Cart/CartState";
import CheckoutReviewAndSubmitState from "@insite/client-framework/Store/Pages/CheckoutReviewAndSubmit/CheckoutReviewAndSubmitState";
import CheckoutShippingState from "@insite/client-framework/Store/Pages/CheckoutShipping/CheckoutShippingState";
import DealerDetailsState from "@insite/client-framework/Store/Pages/DealerDetails/DealerDetailsState";
import InvoiceDetailsState from "@insite/client-framework/Store/Pages/InvoiceDetails/InvoiceDetailsState";
import InvoiceHistoryState from "@insite/client-framework/Store/Pages/InvoiceHistory/InvoiceHistoryState";
import LocationFinderState from "@insite/client-framework/Store/Pages/LocationFinder/LocationFinderState";
import MyListDetailsState from "@insite/client-framework/Store/Pages/MyListDetails/MyListDetailsState";
import MyListsState from "@insite/client-framework/Store/Pages/MyLists/MyListsState";
import OrderApprovalDetailsState from "@insite/client-framework/Store/Pages/OrderApprovalDetails/OrderApprovalDetailsState";
import OrderApprovalListState from "@insite/client-framework/Store/Pages/OrderApprovalList/OrderApprovalListState";
import OrderConfirmationState from "@insite/client-framework/Store/Pages/OrderConfirmation/OrderConfirmationState";
import OrderDetailsState from "@insite/client-framework/Store/Pages/OrderDetails/OrderDetailsState";
import OrderHistoryState from "@insite/client-framework/Store/Pages/OrderHistory/OrderHistoryState";
import OrderStatusState from "@insite/client-framework/Store/Pages/OrderStatus/OrderStatusState";
import OrderUploadState from "@insite/client-framework/Store/Pages/OrderUpload/OrderUploadState";
import ProductDetailsState from "@insite/client-framework/Store/Pages/ProductDetails/ProductDetailsState";
import ProductListState from "@insite/client-framework/Store/Pages/ProductList/ProductListState";
import QuickOrderState from "@insite/client-framework/Store/Pages/QuickOrder/QuickOrderState";
import RequestRmaState from "@insite/client-framework/Store/Pages/RequestRma/RequestRmaState";
import RequisitionConfirmationState from "@insite/client-framework/Store/Pages/RequisitionConfirmation/RequisitionConfirmationState";
import RequisitionsState from "@insite/client-framework/Store/Pages/Requisitions/RequisitionsState";
import RfqConfirmationState from "@insite/client-framework/Store/Pages/RfqConfirmation/RfqConfirmationState";
import RfqJobQuoteDetailsState from "@insite/client-framework/Store/Pages/RfqJobQuoteDetails/RfqJobQuoteDetailsState";
import RfqJobQuotesState from "@insite/client-framework/Store/Pages/RfqJobQuotes/RfqJobQuotesState";
import RfqMyQuotesState from "@insite/client-framework/Store/Pages/RfqMyQuotes/RfqMyQuotesState";
import RfqQuoteDetailsState from "@insite/client-framework/Store/Pages/RfqQuoteDetails/RfqQuoteDetailsState";
import RfqRequestQuoteState from "@insite/client-framework/Store/Pages/RfqRequestQuote/RfqRequestQuoteState";
import SavedOrderDetailsState from "@insite/client-framework/Store/Pages/SavedOrderDetails/SavedOrderDetailsState";
import SavedOrderListState from "@insite/client-framework/Store/Pages/SavedOrderList/SavedOrderListState";
import SavedPaymentsState from "@insite/client-framework/Store/Pages/SavedPayments/SavedPaymentsState";
import SignInState from "@insite/client-framework/Store/Pages/SignIn/SignInState";
import StaticListState from "@insite/client-framework/Store/Pages/StaticList/StaticListState";
import UserListState from "@insite/client-framework/Store/Pages/UserList/UserListState";
import UserSetupState from "@insite/client-framework/Store/Pages/UserSetup/UserSetupState";

export default interface PagesState {
    readonly accountSettings: AccountSettingsState;
    readonly addresses: AddressesState;
    readonly brands: BrandsState;
    readonly budgetManagement: BudgetManagementState;
    readonly cart: CartState;
    readonly checkoutReviewAndSubmit: CheckoutReviewAndSubmitState;
    readonly checkoutShipping: CheckoutShippingState;
    readonly dealerDetails: DealerDetailsState;
    readonly invoiceDetails: InvoiceDetailsState;
    readonly invoiceHistory: InvoiceHistoryState;
    readonly locationFinder: LocationFinderState;
    readonly myLists: MyListsState;
    readonly myListDetails: MyListDetailsState;
    readonly orderApprovalList: OrderApprovalListState;
    readonly orderApprovalDetails: OrderApprovalDetailsState;
    readonly orderDetails: OrderDetailsState;
    readonly orderConfirmation: OrderConfirmationState;
    readonly orderHistory: OrderHistoryState;
    readonly orderStatus: OrderStatusState;
    readonly orderUpload: OrderUploadState;
    readonly productDetails: ProductDetailsState;
    readonly productList: ProductListState;
    readonly quickOrder: QuickOrderState;
    readonly requestRma: RequestRmaState;
    readonly requisitionConfirmation: RequisitionConfirmationState;
    readonly requisitions: RequisitionsState;
    readonly rfqConfirmation: RfqConfirmationState;
    readonly rfqJobQuotes: RfqJobQuotesState;
    readonly rfqJobQuoteDetails: RfqJobQuoteDetailsState;
    readonly rfqMyQuotes: RfqMyQuotesState;
    readonly rfqQuoteDetails: RfqQuoteDetailsState;
    readonly rfqRequestQuote: RfqRequestQuoteState;
    readonly savedOrderList: SavedOrderListState;
    readonly savedOrderDetails: SavedOrderDetailsState;
    readonly savedPayments: SavedPaymentsState;
    readonly signIn: SignInState;
    readonly staticList: StaticListState;
    readonly userList: UserListState;
    readonly userSetup: UserSetupState;
}
