{
 "title": "Performance dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Mappers",
   "type": "graph",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isc_duration_seconds_sum{type=~\".*Mapper\"}/isc_duration_seconds_count{type=~\".*Mapper\"}",
     "legendFormat": "{{type}} {{method}}"
    }
   ]
  },
  {
   "title": "Handler Chain",
   "type": "graph",
   "gridPos": { "h": 13, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isc_duration_seconds_sum{type=~\".*Service\"}/isc_duration_seconds_count{type=~\".*Service\"}",
     "legendFormat": "{{type}} {{method}}"
    }
   ]
  },
  {
   "title": "Pipeline",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isc_duration_seconds_sum{method=\"ExecutePipeline\"}/isc_duration_seconds_count{method=\"ExecutePipeline\"}",
     "legendFormat": "{{type}} {{method}}"
    }
   ]
  },
  {
   "title": "Handlers and Pipes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "isc_duration_seconds_sum{type!~\".*Mapper|.*Service|ExecutePipeline\"}/isc_duration_seconds_count{type!~\".*Mapper|.*Service|ExecutePipeline\"}",
     "legendFormat": "{{type}} {{method}}"
    }
   ]
  },
  {
   "title": "Handler, handler chain, pipe, pipeline, mappers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum without () (isc_duration_seconds_sum)) / (sum without ()(isc_duration_seconds_count))",
     "legendFormat": "{{type}} {{method}}"
    }
   ]
  }
 ]
}